### ISSUE TITLE
Use `method` and `path` labels instead of `RouteActionMethod`

### ISSUE THREAD

**Issue by jsw** [stijndehaes/play-prometheus-filters#12]
Have you considered using `method` and `path` labels instead of `RouteActionMethod`? Generally, the action method names aren't well known or unique. I like the use of `method` and `path` in this tutorial by a Prometheus co-creator

https://www.digitalocean.com/community/tutorials/how-to-query-prometheus-on-ubuntu-14-04-part-1

**Comment by stijndehaes** [comment]
This pull request (https://github.com/stijndehaes/play-prometheus-filters/pull/13) added extra labels. You can test out the 0.4.0 release if you want.
