### ISSUE TITLE
Crash in tests

### ISSUE THREAD

**Issue by stijndehaes** [stijndehaes/play-prometheus-filters#2]
injecting constructor, java.lang.IllegalArgumentException: Collector already registered that provides name: requests_latency_seconds_count

Because in tests multiple play apps can start. Make sure to only register collectors once

**Comment by DrewDennison** [comment]
I'm also seeing this but with play's hot reload. I'm using 0.2.x. It would be great to only register once. Happy to help if you have questions about my setup. I love what you've built!

**Comment by stijndehaes** [comment]
@DrewDennison I will look into this sometime this week :) I fixed it in the tests by disabling the filters in my test application.conf. For a quick workaround you could only enable the filters in production mode and not in development mode.

**Comment by DrewDennison** [comment]
Awesome! Thanks. Yep that's what I did too.

**Comment by stijndehaes** [comment]
I added this to the module: CollectorRegistry.defaultRegistry.clear()
This clears everything registered to the registry on startup. This should fix the issue. Although this means you should register your metrics after the startup of the module. I released it in 0.2.1 and 0.3.1

**Comment by stijndehaes** [comment]
@DrewDennison Closing this, feel free to reopen it if you think there is something wrong with my solution
