### ISSUE TITLE
New maintainer? 

### ISSUE THREAD

**Issue by SoerenSilkjaer** [stijndehaes/play-prometheus-filters#23]
Is this project abandoned?

**Comment by victorhearnyeates** [comment]
I'd like to know this as well

**Comment by stijndehaes** [comment]
I don't use play anymore and don't really seem to find the time to maintain this anymore. So feel free to start a fork and I will add that fork to the readme.

**Comment by SoerenSilkjaer** [comment]
@stijndehaes Hi stijndehaes. My company will be carrying the torch foward. We made this fork, and we published our first releases to sonatype already. https://github.com/Jyllands-Posten/play-prometheus-filters

Can you link to this repo in your readme?

**Comment by stijndehaes** [comment]
@SoerenSilkjaer I have added you guys in the README. I will probably set this project to read only in the following week. Thank you for picking up the torch :)
